config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts

  get 'u/:username' => 'public#profile', as: :profile
  resources :communities do
    resources :posts
  end

  resources :subscriptions
  resources :comments, only: [:create]

  post 'post/vote' => 'votes#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'public#index'
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :communities, through: :subscriptions
  has_many :posts
  has_many :comments
  has_many :votes

  validates_presence_of :first_name, :last_name, :username

  def full_name
    "#{first_name} #{last_name}"
  end

  def upvoted_post_ids
    votes.where(upvote: true).pluck(:post_id)
  end

  def downvoted_post_ids
    votes.where(upvote: false).pluck(:post_id)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :account

  validates_presence_of :message, :account_id, :post_id

end

app/models/community.rb
class Community < ApplicationRecord
  belongs_to :account
  has_many :subscriptions
  has_many :posts
  has_many :subscribers, through: :subscriptions, source: :account

  validates_presence_of :url, :name, :rules
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :account
  belongs_to :community
  has_many :comments
  validates_presence_of :title, :body, :account_id, :community_id

  def score
    if upvotes.positive? || downvotes.positive?
      upvotes.positive? ? (upvotes - downvotes) : (downvotes * -1)
    else
      0
    end
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :account
  belongs_to :community
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :account
  belongs_to :post

  validates_uniqueness_of :account_id, scope: :post_id

  after_create :increment_vote, :add_karma
  after_destroy :decrement_vote, :remove_karma

  private

  def increment_vote
    field = upvote ? :upvotes : :downvotes
    Post.find(post_id).increment(field).save
  end

  def decrement_vote
    field = upvote ? :upvotes : :downvotes
    Post.find(post_id).decrement(field).save
  end

  def add_karma
    account = Account.find(account_id)
    account.increment(:karma, 1).save
  end

  def remove_karma
    account = Account.find(account_id)
    account.decrement(:karma, 1).save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new comment_params
    @comment.account_id = current_account.id

    respond_to do |format|
      format.js {
        if @comment.save
          @comments = Comment.where(post_id: @comment.post_id)
          render 'comments/create'
        else
          # unable to save
        end
      }
    end
  end

  def comment_params
    params.require(:comment).permit(:message, :post_id)
  end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :authenticate_account!, except: [:index, :show]
  before_action :set_community, only: [:show]

  def index
    @communities = Community.all
  end

  def show
    @posts = @community.posts.limit(20).sort_by(&:score).reverse
    @subscriber_count = @community.subscribers.count
    @is_subscribed = account_signed_in? ? Subscription.where(community_id: @community.id, account_id: current_account.id).any? : false
    @subscription = Subscription.new
  end

  def new
    @community = Community.new
  end

  def create
    @community = Community.new community_values
    @community.account_id = current_account.id

    if @community.save
      redirect_to communities_path
    else
      render :new
    end
  end

  private

  def set_community
    @community = Community.find(params[:id])
  end

  def community_values
    params.require(:community).permit(:name, :url, :summary, :rules)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_account!, except: [:index, :show]
  before_action :set_post, only: [:show]
  before_action :auth_subscriber, only: [:new]

  def index
    @posts = Post.all
  end

  def show
    @comment = Comment.new
  end

  def new
    @community = Community.find(params[:community_id])
    @post = Post.new
  end

  def create
    @post = Post.new post_values
    @post.account_id = current_account.id
    @post.community_id = params[:community_id]

    if @post.save
      redirect_to community_path(@post.community_id)
    else
      @post.community_id = params[:community_id]
      render :new
    end
  end

  private

  def set_post
    @post = Post.includes(:comments).find(params[:id])
  end

  def auth_subscriber
    unless Subscription.where(community_id: params[:community_id], account_id: current_account.id).any?
      redirect_to root_path, flash: { danger: 'You are not authorized to view this page.'}
    end
  end

  def post_values
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController

  def index
    @communities = Community.all.limit(5)
    @posts = Post.limit(20).sort_by(&:score).reverse
  end

  def profile
    @profile = Account.find_by_username params[:username]
    @posts = @profile.posts
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    post_id = params[:post_id]
    vote = Vote.new(post_id: post_id, upvote: params[:upvote], account_id: current_account.id)
    existing_vote = Vote.where(account_id: current_account.id, post_id: post_id)
    @new_vote = existing_vote.empty?
    respond_to do |format|
      format.js {
        existing_vote.empty? ? @success = vote.save : existing_vote.first.destroy
        @post = Post.find(post_id)
        @is_upvote = params[:upvote]
        render 'votes/create'
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
  def upvoted? post
    account_signed_in? && current_account.upvoted_post_ids.include?(post.id) ? ' active' : ''
  end

  def downvoted? post
    account_signed_in? && current_account.downvoted_post_ids.include?(post.id) ? ' active' : ''
  end
end

app/views/layouts/_footer.html.erb
footer

app/views/layouts/_header.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 pt-3 pb-3">
      <div class="float-right">
        <% if account_signed_in? %>
          <div class="dropdown show float-right">
            <a class="btn btn-white dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_account.full_name %>
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <%= link_to "Profile", profile_path(current_account.username), class: "dropdown-item" %>
              <%= link_to "Settings", edit_account_registration_path, class: "dropdown-item" %>
              <%= link_to "Sign Out", destroy_account_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </div>
          <div class="karma float-left mt-2 mr-2">
            <span class="fa fa-star text-warning"></span>
            <%= current_account.karma %>
          </div>
        <% else %>
          <%= link_to "Log In", new_account_session_path, class: "btn btn-outline-primary" %>
          <%= link_to "Sign Up", new_account_registration_path, class: "btn btn-outline-primary" %>
        <% end %>
      </div>
      <p class="h3"><%= link_to "Reddit Clone", root_path %></p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Creddit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>

    <section class="bg-light">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 pt-4">
            <%= yield %>
          </div>
        </div>
      </div>
    </section>

    <%= render partial: 'layouts/footer' %>
  </body>
</html>